language: python

# Run travis, run
# Run converalls, run
# Use container-based infrastructure
sudo: false

notifications:
  email:
    on_success: never

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install coveralls
script:
  - coverage run --source=. runtests.py
after_success:
  - coveralls
